name: Test Cached VHDX

on:
  push:
    branches:
      - main
    paths:
      - '**/test-cache.yml'

  workflow_dispatch:

jobs:
  test-cache:
    runs-on: windows-2025
    steps:
    - name: Restore VHDX from Cache
      uses: actions/cache/restore@v4
      with:
        path: D:\dev_drive.vhdx
        key: vhdx-cache
        fail-on-cache-miss: true

    - name: Mount VHDX
      run: |
        $Drive = Mount-VHD -Path D:\dev_drive.vhdx -PassThru
        $Drive | Get-Disk | Get-Partition | Where-Object { $_.Type -eq 'Basic' } | Set-Partition -NewDriveLetter 'X'
        Get-Disk | Get-Partition
        ls -l X:\

    - name: Update PATH
      run: |
        Write-Output "X:\tools\dotnet" >> $env:GITHUB_PATH
        Write-Output "X:\tools\PowerShell7" >> $env:GITHUB_PATH
        Write-Output "X:\tools\Git\bin" >> $env:GITHUB_PATH
        Write-Output "X:\tools\Git\cmd" >> $env:GITHUB_PATH
        Write-Output "X:\tools\Git\mingw64\bin" >> $env:GITHUB_PATH
        Write-Output "X:\tools\node" >> $env:GITHUB_PATH

    - name: Verify Tool Installations
      run: |
        Get-Command git.exe
        Get-Command node.exe
        Get-Command dotnet.exe
        Get-Command msbuild.exe
